### ISSUE TITLE
cant seem to connect

### ISSUE THREAD

**Issue by zeltak** [3ll3d00d/jriver_homeassistant#12]
Hi and thank you again for your amazing work!

for some reason I cant seem to ever connect to my server. I have everything configured:ֿ

![CleanShot 2024-01-14 at 22 38 07@2x](https://github.com/3ll3d00d/jriver_homeassistant/assets/498410/f3f36cfe-ad23-425b-9a41-a127ffeb8668)

have the correct IP but in home assistant it always fails to connect

![CleanShot 2024-01-14 at 22 39 37@2x](https://github.com/3ll3d00d/jriver_homeassistant/assets/498410/31e290ff-b747-4328-badf-977a2fcbb746)

![CleanShot 2024-01-14 at 22 40 03@2x](https://github.com/3ll3d00d/jriver_homeassistant/assets/498410/17d7c89b-cef1-4107-b46f-085def702d19)

I have MCWS running for years with no issues 

any clue?

thx so much !

Z

**Comment by 3ll3d00d** [comment]
need to see the error(s) from the home assistant logs, pls share them

I made one change in 0.0.7 which guards against a value being not present in a particular MCWS response which is a possible cause, you can try upgrading to that also

**Comment by zeltak** [comment]
yeah that worked!

thank you so much for working on this, life became a lot sweeter thx to you :) :)
