### ISSUE TITLE
Any advise on the config for the MC server in a VM?

### ISSUE THREAD

**Issue by rudydevolder** [3ll3d00d/jriver_homeassistant#19]
I want to run my MC-server on a debian VM in my ProxMox server

1. Minimum version # for MC
2. Can it be headless? UI needed?
3. If headless are there limitations?
4. Which one? jriver-x11vnc versus jriver-xvnc
5. Any other things? Like choice of audio card?

**Comment by 3ll3d00d** [comment]
1. best results are achieved with MC32 or higher as that provides the MCWS Browse/Rules call which is used to automate detection of playlists for display in HA, earlier versions should work fine though. I only actively test against latest though.
2. I don't believe MC on linux can run truly headless, I don't run it like this though so don't know details, there are some posts on the MC linux board from people who aim for this
3. N/A
4. see https://yabb.jriver.com/interact/index.php?topic=125124.0
5. depends on your needs and what type of interface you want, best to ask on interact if unsure

Qs 2 onwards are better handled on interact so suggest posting there
