### ISSUE TITLE
KeyError: 'api_key'

### ISSUE THREAD

**Issue by rh8056** [3ll3d00d/jriver_homeassistant#9]
I just installed the latest update (v0.0.5) from v0.0.1. After rebooting HA, on the Integration page it says "failured to load." I attempted to go through the setup options again and on the third page I get this:

![image](https://github.com/3ll3d00d/jriver_homeassistant/assets/25002758/b4adebe3-a646-49df-af41-100e330d4925)

In the log files of HA, I see the following error:

```
Logger: custom_components.jriver.config_flow
Source: custom_components/jriver/config_flow.py:554
Integration: JRiver Media Center ([documentation](https://github.com/3ll3d00d/jriver_homeassistant/), [issues](https://github.com/3ll3d00d/jriver_homeassistant/issues))
First occurred: 10:43:49 AM (1 occurrences)
Last logged: 10:43:49 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/jriver/config_flow.py", line 554, in _ensure_library_fields
    ms, _ = await validate_http(self.hass, self.config_entry.data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jriver/config_flow.py", line 109, in validate_http
    access_key = data[CONF_API_KEY]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'api_key'
```

**Comment by 3ll3d00d** [comment]
Probably have to deal with there being no API key at all, will check it

**Comment by 3ll3d00d** [comment]
try https://github.com/3ll3d00d/jriver_homeassistant/releases/tag/0.0.6

**Comment by rh8056** [comment]
That did the trick. Thanks!
